### PR TITLE
Scala 2.12

### LINKED ISSUE #27: Scala 2.12 version?
Any plans to crossbuild for 2.12?

### PR DESCRIPTION
**Pull request by andrebeat**
This PR updates the Scala version to 2.12. Additionally, I also updated the sbt version and fixed all deprecations. Fixes #27.

### CODE REVIEW

**Comment by kiequoo** [comment]
I would be very happy if this gets merged!

**Comment by jrudolph** [comment]
Thanks, @andrebeat. Looking good. I'll publish the new version asap.

**Comment by jrudolph** [comment]
The new release is on sonatype: https://oss.sonatype.org/content/repositories/releases/net/virtual-void/json-lenses_2.12/0.6.2/

Will push the merge and update of the README once it is on maven central.

**Comment by andrebeat** [comment]
👍

**Pull request merged**
